apiVersion: v1
kind: Pod
metadata:
  name: "nginx"
  namespace: vsm-app-ns
  labels:
    app: "nginx"
spec:
  containers:
  - name: nginx
    image: "nginx:latest"
    ports:
    - containerPort:  80
      name:  http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: vsm-app-ns
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: nginx
    port: 80
    targetPort: 80
    protocol: TCP
